name: pipl
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Pipl
      fonts:
        - asset: fonts/Pipl.ttf

    - family: HK Grotesk
      fonts:
        - asset: fonts/HKGrotesk.ttf

    - family: Netherland Cracker
      fonts:
        - asset: fonts/NetherlandCracker.ttf